### ISSUE TITLE
[nice-to-have] package.json with dependencies

### ISSUE THREAD

**Issue by alfongj** [googlesamples/identity-toolkit-node#6]
In addition to pointing out [in the docs](https://developers.google.com/identity/toolkit/web/quickstart/nodejs) which packages need to be installed, it could be helpful if there was a [package.json](http://browsenpm.org/package.json) with the dependencies already listed.

This way the developers should only have to run `npm install` once, instead of having to install all dependencies manually.

Also, I would day this is probably the first place where nodejs devs will look for dependencies in a repository.

**Comment by jin-liu** [comment]
Fair point. Working on the fix.

**Comment by jin-liu** [comment]
Done.
